# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fdc6992fb0e4aa613aaa816e9607e33f3e2a5d56bb0ebdd078847e98c31706cf9a10e532bbdbc92742a7ca29893238667699f8bfc75d5247ae257ac9b68d28

test:
  secret_key_base: 6e4ee48295bc23dec125e972a60d3ecaf119cba10717d33f7f577b98de61a52f2fc0426ff807fe581dde5acf39c98fde2fedecb55335b638b585251b7bf5fcf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
